"""Team username addition

Revision ID: 100543d3d9e4
Revises: 22766c1d9b43
Create Date: 2020-07-22 17:30:57.439275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '100543d3d9e4'
down_revision = '22766c1d9b43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('username', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_team_username'), 'team', ['username'], unique=True)
    op.drop_index('ix_team_team_name', table_name='team')
    op.create_index(op.f('ix_team_team_name'), 'team', ['team_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_team_name'), table_name='team')
    op.create_index('ix_team_team_name', 'team', ['team_name'], unique=1)
    op.drop_index(op.f('ix_team_username'), table_name='team')
    op.drop_column('team', 'username')
    # ### end Alembic commands ###
