"""Workout change

Revision ID: 22766c1d9b43
Revises: 3d7629fdbc18
Create Date: 2020-07-17 17:17:26.699591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22766c1d9b43'
down_revision = '3d7629fdbc18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('athlete_id', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_workout_id'), 'workout', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_id'), table_name='workout')
    op.drop_column('workout', 'athlete_id')
    # ### end Alembic commands ###
