"""Team and Workout

Revision ID: 3d7629fdbc18
Revises: 
Create Date: 2020-07-17 17:04:51.426142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d7629fdbc18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(length=64), nullable=True),
    sa.Column('team_size', sa.Integer(), nullable=True),
    sa.Column('trainer', sa.String(length=64), nullable=True),
    sa.Column('trainer_email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('athlete_userids', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_team_name'), 'team', ['team_name'], unique=True)
    op.create_index(op.f('ix_team_trainer_email'), 'team', ['trainer_email'], unique=False)
    op.create_table('workout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_name', sa.String(length=50), nullable=True),
    sa.Column('parameters', sa.String(length=100), nullable=True),
    sa.Column('entries', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_timestamp'), 'workout', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_timestamp'), table_name='workout')
    op.drop_table('workout')
    op.drop_index(op.f('ix_team_trainer_email'), table_name='team')
    op.drop_index(op.f('ix_team_team_name'), table_name='team')
    op.drop_table('team')
    # ### end Alembic commands ###
