"""Exercisesv2

Revision ID: 8c262f1be497
Revises: d042ea57faa9
Create Date: 2020-08-01 15:28:13.270763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c262f1be497'
down_revision = 'd042ea57faa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_name', sa.String(length=30), nullable=True),
    sa.Column('parameter', sa.String(length=30), nullable=True),
    sa.Column('value', sa.String(length=20), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_id'), 'exercise', ['id'], unique=False)
    op.drop_index('ix_exercises_id', table_name='exercises')
    op.drop_table('exercises')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('exercise_name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('parameter', sa.VARCHAR(length=30), nullable=True),
    sa.Column('value', sa.VARCHAR(length=20), nullable=True),
    sa.Column('unit', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exercises_id', 'exercises', ['id'], unique=False)
    op.drop_index(op.f('ix_exercise_id'), table_name='exercise')
    op.drop_table('exercise')
    # ### end Alembic commands ###
